import { faCircleInfo } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export default function Footer() {
    return (
        <footer>
            <FontAwesomeIcon icon={faCircleInfo} width={17} height={17} />
            <p>This page, like all my projects, was not assisted or generated by AI</p>
        </footer>
    );
}